services:

  postgres-sistema:
    image: postgres:15
    container_name: postgres-sistema
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome123
    networks:
      - backend

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  usuarios-servicio:
    build: ./usuarios-servicio
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres-sistema
    networks:
      - backend

  asignaturas-servicio:
    build: ./asignaturas-servicio
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres-sistema
    networks:
      - backend

  matriculas-servicio:
    build: ./matriculas-servicio
    ports:
      - "8083:8083"
    depends_on:
      - usuarios-servicio
      - asignaturas-servicio
      - eureka-server
      - postgres-sistema
    networks:
      - backend

  auth-service:
    build: ./auth_service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres-sistema
    networks:
      - backend
networks:
  backend:
    driver: bridge
