version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-sistema
    restart: always
    environment:
      POSTGRES_DB: sistema_educativo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
